version: '3.8'
services:
  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/posgresql/data
  server:
    build: .
    restart: always
    container_name: server
    command: node src/app
    depends_on:
      - db
    environment:
      - TOKEN_SECRET=${TOKEN_SECRET}
    ports:
      - '8080:8080'
volumes:
  db:
    driver: local