version: '3.3'
services:
  db:
    container_name: db
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db:/var/lib/posgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    container_name: server
    build: 
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    command: npm run start
    depends_on:
      - db
    environment:
      - TOKEN_SECRET=${TOKEN_SECRET}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${SERVER_PORT_WITH_SSL}:${SERVER_PORT_WITH_SSL}
  migration:
    build: 
      context: .
      dockerfile: Dockerfile.migration
    command: ["sh", "-c", "make migration-prepare"]
    depends_on:
      - db
      - server
volumes:
  db:
    driver: local